### PR TITLE
Added tests for sriov.go

### PR DESCRIPTION
**Pull request by pmossakx**
This change adds tests (part of them) for sriov.go.
Test filesystem (testing.go) now uses chroot.
This was needed to overcome limitations for sriov.go functions
that invoked utils.go functions.

Using chroot causes another issue with creating new namespace.
This needs further refactoring - until then blocked tests
have been disabled (pending in ginkgo).

Refactored sriov.go and config.go to simplify netlink testing.

Implements: MSP-12413

Signed-off-by: Piotr Mossakowski <piotrx.mossakowski@intel.com>

### CODE REVIEW

**Comment by pmossakx** [comment]
make test-coverage
```
running gofmt...
setting GOPATH...
building golint...
running golint...
building gocovmerge...
building gocov...
building gocov-xml...
running coverage tests...
ok      github.com/intel/sriov-cni/pkg/config   0.007s  coverage: 93.8% of statements in github.com/intel/sriov-cni/pkg/config
ok      github.com/intel/sriov-cni/pkg/dpdk     0.016s  coverage: 87.0% of statements in github.com/intel/sriov-cni/pkg/dpdk
ok      github.com/intel/sriov-cni/pkg/sriov    0.009s  coverage: 35.2% of statements in github.com/intel/sriov-cni/pkg/sriov
ok      github.com/intel/sriov-cni/pkg/utils    0.006s  coverage: 66.9% of statements in github.com/intel/sriov-cni/pkg/utils
```

**Comment by pmossakx** [comment]
It seems that travis ignores chroot in [testing.go#L85](https://github.com/intel/sriov-cni/pull/61/files#diff-055758c2a72b256b8d1ebced1b8ed832R85):
https://travis-ci.org/intel/sriov-cni/builds/489063529#L521

**Comment by lennybe** [comment]
Please ignore E2E test

**Comment by ahalim-intel** [comment]
I've included this commit into #71. Closing this one.

**Pull request closed without merging**
