### PR TITLE
Adding support to set the MTU for the VFs

### PR DESCRIPTION
**Pull request by svallala**
Adding support to set the MTU for the VFs. This will get rid of the need to use tuning plugin to achieve the same and will provide a way to reset the value back as part of ReleaseVF

### CODE REVIEW

**Comment by adrianchiris** [comment]
So, restoring an interface's MTU value is something that may be generally desired ?
(i.e not limited to SR-IOV interfaces?)

**Comment by moshe010** [comment]
@adrianchiris in which cases? I think the tuning plugin will handle mostly veth pair which remove completely.

**Comment by adrianchiris** [comment]
@moshe010 was thinking of host-device plugin (also for k8s over VM with SR-IOV PT if host device CNI is used)

**Comment by moshe010** [comment]
Yes I forgot about that one :)

**Comment by ahalim-intel** [comment]
@zshi-redhat ptal

**Comment by killianmuldoon** [comment]
closed in line with #123. We don't have a clean implementation of this for SR-IOV CNI and - as it's a kernel only concern - the tuning cni used in a chained plugin config is the best solution right now.

**Pull request closed without merging**
