### PR TITLE
remove vendor dependencies for build/lint/test rules in Makefile

### PR DESCRIPTION
**Pull request by zshi-redhat**

### CODE REVIEW

**Comment by ahalim-intel** [comment]
Without vendor the build will fail. Why do we need to remove vendor from build dependencies?

**Comment by zshi-redhat** [comment]
> Without vendor the build will fail. Why do we need to remove vendor from build dependencies?

I think we expect that user doesn't have to do glide update when building binary locally. 
All the vendor pkg update shall be committed along with the actual feature code change via PR.
This doesn't remove vendor update rule in Makefile, it can still be updated via `make vendor`, but this will likely be used by developers to run the glide update.

**Comment by ahalim-intel** [comment]
I think make dependencies are behaving as expected. The reason [this build](https://travis-ci.com/intel/sriov-cni/builds/119505890) failed because the glide files were updated where the required updates in the vendor were missing. So `make` did the correct course of action by trying to `glide update` because vendor weren't updated. If you look at other build history, the `glide update` is not triggered for all build.
We just need to make sure that vendor dir is updated whenever dependencies are updated in the glide.yaml and glide.lock. IMO having the vendor prerequisite helps us identifying this kind of issue from travis-ci. What do you think?

**Comment by zshi-redhat** [comment]
> I think make dependencies are behaving as expected. The reason [this build](https://travis-ci.com/intel/sriov-cni/builds/119505890) failed because the glide files were updated where the required updates in the vendor were missing. So `make` did the correct course of action by trying to `glide update` because vendor weren't updated. If you look at other build history, the `glide update` is not triggered for all build.

In `Makefile`, `glide update` is triggered due to `glide.lock` or `glide.yaml` file changes, not a missing vendor pkg. When the timestamp of vendor pkg folder is older than `glide.lock` or `glide.yaml`, even if there is no vendor pkg missing (meaning build can pass without updating vendor pkg), `glide update` will also be triggered. In such case, I think we shall not trigger vendor update.

Let's say if there is indeed a vendor pkg missing, then we shall expect the building of binary fail, not `glide update` is executed. because the reason why vendor pkg gets updated is that new code imports a new vendor pkg. If we allow every build to update vendor pkg via `glide update`, then there might be case that it doesn't report missing vendor pkg failure when building binary.

> We just need to make sure that vendor dir is updated whenever dependencies are updated in the glide.yaml and glide.lock. IMO having the vendor prerequisite helps us identifying this kind of issue from travis-ci. What do you think?

**Pull request merged**
