### PR TITLE
WIP: Testing CI

### PR DESCRIPTION
**Pull request by lennybe**

### CODE REVIEW

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by ahalim-intel** [comment]
@lennybe There's permission issue to view Details

**Comment by zshi-redhat** [comment]
Same issue here to review the details: http://13.74.249.42:8080/job/SRIOV-ConnectX-5/69/
While waiting for the details to be available, I'm also wondering what's the test case be executed. shall we consider adding the CI tests in this repo?

**Comment by lennybe** [comment]
> Same issue here to review the details: http://13.74.249.42:8080/job/SRIOV-ConnectX-5/69/
> While waiting for the details to be available, I'm also wondering what's the test case be executed. shall we consider adding the CI tests in this repo?

Yeah, thanks, 
I am working on it, looks like internal firewall issues. Not related to Intel.
I will update you when it will be fixed.

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by zshi-redhat** [comment]
> recheck

here you go, the latest recheck result can be reviewed now!

**Comment by lennybe** [comment]
@zshi-redhat @ahalim-intel 
Permission issue is fixed. You should be able to see 'details' now.

**Comment by zshi-redhat** [comment]
> @zshi-redhat @ahalim-intel
> Permission issue is fixed. You should be able to see 'details' now.

So is there any configuration you did in this github repo in order to enable the CI tests? Is it worth documenting the process?

**Comment by lennybe** [comment]
> > @zshi-redhat @ahalim-intel
> > Permission issue is fixed. You should be able to see 'details' now.
> 
> So is there any configuration you did in this github repo in order to enable the CI tests? Is it worth documenting the process?

Yes,
@ahalim-intel added 'mellanox-ci' as a collaborator to the repo.

**Comment by zshi-redhat** [comment]
> > > @zshi-redhat @ahalim-intel
> > > Permission issue is fixed. You should be able to see 'details' now.
> > 
> > 
> > So is there any configuration you did in this github repo in order to enable the CI tests? Is it worth documenting the process?
> 
> Yes,
> @ahalim-intel added 'mellanox-ci' as a collaborator to the repo.

Thanks @lennybe!  what's your plan of adding more test cases in CI?

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
recheck

**Comment by lennybe** [comment]
retest

**Pull request closed without merging**
